namespace: de_claasklar
name: devtools
version: 0.1.0
readme: README.md
authors:
- claasklar <git@claasklar.de>
description: Collection of modules for using the arch linux devtools
license_file: 'LICENSE'
tags: ['arch', 'devtools']